version: "3"

services:

  db_postgres:
    image: postgres:14.0
    container_name: db_postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./Database/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
      - ./Database/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
  backend:
    build: backend/.
    container_name: backend
    ports:
      - 8080:8080
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_postgres:5432/
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: prod #dev, prod, h2, heroku
    depends_on:
      - db_postgres

  frontend:
    build: frontend/.
    container_name: frontend
    ports:
      - 4200:80
    links:
      - backend
    depends_on:
      - backend
